const BaseRepository = require('./base.repository');
const {
  User, Role, Property, Apartment, Tenant, Lease,
  Payment, Maintenance, Expense, Equipment, Task, Upload, CalendarEvent,
  Notification, Salary, UtilityBill, PaymentHistory, TaskHistory,
  AuditLog, RefreshToken, Permission, RolePermission,
  Service, Equipe, Planning, Pointage, Conge,
  WorkflowValidation, WorkflowEtape, MessageInterne, GPSTracking,
} = require('../models');

module.exports = {
  userRepo: new BaseRepository(User),
  roleRepo: new BaseRepository(Role),
  propertyRepo: new BaseRepository(Property),
  apartmentRepo: new BaseRepository(Apartment),
  tenantRepo: new BaseRepository(Tenant),
  leaseRepo: new BaseRepository(Lease),
  paymentRepo: new BaseRepository(Payment),
  maintenanceRepo: new BaseRepository(Maintenance),
  expenseRepo: new BaseRepository(Expense),
  equipmentRepo: new BaseRepository(Equipment),
  taskRepo: new BaseRepository(Task),
  uploadRepo: new BaseRepository(Upload),
  calendarRepo: new BaseRepository(CalendarEvent),
  notificationRepo: new BaseRepository(Notification),
  salaryRepo: new BaseRepository(Salary),
  utilityBillRepo: new BaseRepository(UtilityBill),
  paymentHistoryRepo: new BaseRepository(PaymentHistory),
  taskHistoryRepo: new BaseRepository(TaskHistory),
  // Nouveaux repos SMG IMMOBILIER
  auditLogRepo: new BaseRepository(AuditLog),
  refreshTokenRepo: new BaseRepository(RefreshToken),
  permissionRepo: new BaseRepository(Permission),
  rolePermissionRepo: new BaseRepository(RolePermission),
  serviceRepo: new BaseRepository(Service),
  equipeRepo: new BaseRepository(Equipe),
  planningRepo: new BaseRepository(Planning),
  pointageRepo: new BaseRepository(Pointage),
  congeRepo: new BaseRepository(Conge),
  workflowValidationRepo: new BaseRepository(WorkflowValidation),
  workflowEtapeRepo: new BaseRepository(WorkflowEtape),
  messageInterneRepo: new BaseRepository(MessageInterne),
  gpsTrackingRepo: new BaseRepository(GPSTracking),
};
